apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
spec:
  replicas: 2
  selector:
    matchlabels:
      app: backend
  
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: moisesalc/backend-it_talent:latest
        ports:
        - containerPort: 8080
